Repository DumbDogDiner/StickyAPI, pull requests merged in 2021-02, with the labels that each got.

#81 Add GitHub CodeQL and Codacy Static Analysis support
  .github/workflows/code-scanning.yml
Labels: ci/cd

#92 Add support for Stringified NBT objects
  build.gradle
  src/main/java/com/dumbdogdiner/stickyapi/common/nbt/NbtBooleanTag.java
  src/main/java/com/dumbdogdiner/stickyapi/common/nbt/NbtCompoundTag.java
  src/main/java/com/dumbdogdiner/stickyapi/common/nbt/NbtJsonAdapter.java
  src/main/java/com/dumbdogdiner/stickyapi/common/nbt/NbtJsonTag.java
  src/main/java/com/dumbdogdiner/stickyapi/common/nbt/NbtListTag.java
  src/main/java/com/dumbdogdiner/stickyapi/common/nbt/NbtNumberTag.java
  src/main/java/com/dumbdogdiner/stickyapi/common/nbt/NbtPrimitiveTag.java
  src/main/java/com/dumbdogdiner/stickyapi/common/nbt/NbtStringTag.java
  src/main/java/com/dumbdogdiner/stickyapi/common/nbt/NbtTag.java
  src/main/java/com/dumbdogdiner/stickyapi/common/nbt/package-info.java
  src/main/java/com/dumbdogdiner/stickyapi/common/util/StringUtil.java
  src/test/java/com/dumbdogdiner/stickyapi/common/nbt/NbtBooleanTagTest.java
  src/test/java/com/dumbdogdiner/stickyapi/common/nbt/NbtNumberTagTest.java
Labels: feature

#72 Book Text Utils
  .gitignore
  build.gradle
  src/main/java/com/dumbdogdiner/stickyapi/bukkit/item/BookAndQuillBuilder.java
  src/main/java/com/dumbdogdiner/stickyapi/bukkit/item/WrittenBookBuilder.java
  src/main/java/com/dumbdogdiner/stickyapi/bukkit/item/package-info.java
  src/main/java/com/dumbdogdiner/stickyapi/common/util/MathUtil.java
  src/main/java/com/dumbdogdiner/stickyapi/common/util/StringUtil.java
  src/main/java/com/dumbdogdiner/stickyapi/common/util/TextUtil.java
  src/main/java/com/dumbdogdiner/stickyapi/common/util/reflection/package-info.java
  src/main/java/com/dumbdogdiner/stickyapi/common/util/url/URLPair.java
  src/main/java/com/dumbdogdiner/stickyapi/common/util/url/package-info.java
  src/main/java/com/dumbdogdiner/stickyapi/package-info.java
  src/test/java/com/dumbdogdiner/stickyapi/bukkit/item/BookBuilderTest.java
  src/test/java/com/dumbdogdiner/stickyapi/bukkit/item/WrittenBookBuilderTest.java
  src/test/java/com/dumbdogdiner/stickyapi/common/util/StringUtilTest.java
  src/test/java/com/dumbdogdiner/stickyapi/common/util/TextUtilTest.java
  src/test/resources/book1.json
  src/test/resources/rulebook.json
  src/test/resources/rulebook.md
Labels: feature, non-breaking
