Repository DumbDogDiner/StickyAPI, pull requests merged in 2021-01, with the labels that each got.

#66 Remove Powermock from test deps, update dep comments
  build.gradle
Labels: dependencies

#70 Implement PacketInjector & BukkitHandler
  src/main/java/com/dumbdogdiner/stickyapi/bukkit/nms/BukkitHandler.java
  src/main/java/com/dumbdogdiner/stickyapi/bukkit/nms/PacketInjector.java
Labels: feature

#69 PlayerSelector & better math util
  src/main/java/com/dumbdogdiner/stickyapi/bukkit/util/PlayerSelector.java
  src/main/java/com/dumbdogdiner/stickyapi/common/util/MathUtil.java
  src/main/java/com/dumbdogdiner/stickyapi/common/util/NumberUtil.java
Labels: feature

#79 Fix implementation of asynchronous commands for BukkitCommandBuilder and BungeeCommandBuilder
  src/main/java/com/dumbdogdiner/stickyapi/bukkit/command/BukkitCommandBuilder.java
  src/main/java/com/dumbdogdiner/stickyapi/bungeecord/command/BungeeCommandBuilder.java
Labels: p0 bug

#77 Feat/jcx/buildinfo
  .github/workflows/ci.yml
  .github/workflows/publish.yml
  build.gradle
  src/main/java/com/dumbdogdiner/stickyapi/StickyAPI.java
  src/test/java/com/dumbdogdiner/stickyapi/StickyAPITest.java
Labels: CI/CD, dependencies, feature, non-breaking
